version: '3.7'
services:

  # things specific to fastapi
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api:latest

    # ports:
    #   - "8005:8005"
    ipc: host
    network_mode: host
    volumes:
      - ./:/app

    depends_on:
      - triton_server
  
  
  # things specific to triton server
  triton_server:
    # image: nvcr.io/nvidia/tritonserver:23.02-py3
    image: talhayousuf/triton_server_dl
    # ports:
    #   - "8000:8000"
    #   - "8001:8001"
    #   - "8002:8002"

    environment:
      - NVIDIA_VISIBLE_DEVICES=all

    volumes:
    # /models will be used as model-repository
      - ./models:/models
      - .:/workspace

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

    ipc: host
    network_mode: host
    # run triton server in polling mode 
    
    command: tritonserver --model-repository=/models  --model-control-mode=poll --repository-poll-secs=3  --log-verbose=1
  